### ISSUE TITLE
APK download does not work

### ISSUE THREAD

**Issue by jrhbcn** [Admicos/TaskerHTTPServer#2]
Hi, I'm trying to download the latest apk release but the download link does not seem to work. Is it possible to fix it? Many thanks!!

**Comment by neodada** [comment]
@Admicos please look into this.

**Comment by Admicos** [comment]
I don't use or develop this anymore, so don't expect any more updates, but I'll be building an APK in a few minutes.

**Comment by Admicos** [comment]
https://dl.issizler.club/TaskerHTTPServer.apk
