### ISSUE TITLE
Apk download is not working

### ISSUE THREAD

**Issue by jayrajzala** [Admicos/TaskerHTTPServer#3]
download link is broken. please upload it to any other host (other than issizler.com)

**Comment by Admicos** [comment]
https://files.ecmelberk.com/TaskerHTTPServer.apk

The previous domain expired, but I am hoping to keep this up for
longer.

Though since I don't actively maintain this anymore, I won't be making
any promises.

**Comment by jayrajzala** [comment]
> https://files.ecmelberk.com/TaskerHTTPServer.apk The previous domain expired, but I am hoping to keep this up for longer. Though since I don't actively maintain this anymore, I won't be making any promises.

Thank you so much! it works perfectly, just what I needed.
